apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: mysql
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: mysql
        hostPath:
          path: /dev/null
          type: Directory
      containers:
      - name: mysql
        image: mysql:5.7
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          protocol: TCP
      - name: exporter
        image: prom/mysqld-exporter:v0.13.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9104
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: mysql
spec:
  selector:
    app: db
  type: ClusterIP
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: prom
    port: 9104
    protocol: TCP
    targetPort: 9104
