apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
