apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "local"
      - name: exporter
        env:
        - name: DATA_SOURCE_NAME
          value: "root:local@(localhost:3306)"
